<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RobloxPriceTracker.Core/RobloxPriceTracker.Core.csproj" />
    <ProjectReference Include="../RobloxPriceTracker.Infrastructure/RobloxPriceTracker.Infrastructure.csproj" />
  </ItemGroup>
</Project>
